### ISSUE TITLE
can I talk to you ?

### ISSUE THREAD

**Issue by ghost** [ferion11/PCSX2_Appimage#4]
my email: lucasmzainote at gmail.com

**Comment by ferion11** [comment]
Yes. I have send you one email

**Comment by Lucas-bash** [comment]
I was having a little issue with your appimage, there's some game like god
of war in the version opengl that was having very slow fps and a few bugs.
How do I fix it ?

Em domingo, 23 de fevereiro de 2020, DanielDevBR <notifications@github.com>
escreveu:

**Comment by Lucas-bash** [comment]
Do you speak portuguese ? I guess yes because you habe br in your name.

Sabe rapaz eu vou dar uma melhorada na minha maquina aqui, porque eu estou
sozinho e também estou desempregado cerca de um ano e dois meses agora e
minha familha está longe de mim então como não tenho amigos e tal pelo
menos vou ter algo a mais do que ficar atoa em casa, isso vai custar muito
mais talvez meus pais que moram longe me ajudem.

Em domingo, 23 de fevereiro de 2020, Lucas Machado zainote <
lucasmzainote@gmail.com> escreveu:
