### ISSUE TITLE
Stable builds

### ISSUE THREAD

**Issue by TotalCaesar659** [ferion11/PCSX2_Appimage#6]
Do you have a plan for building stable Appimage for 1.6.0, like [GIMP](https://github.com/aferrero2707/gimp-appimage/releases)?

**Comment by ferion11** [comment]
To be honest, no. Because most of the git changes for linux, at this point, are bugfixs and good improvements. It's very hard to get your pull request to be merged, there is a lot of verification and validations. That result on the last version been almost always more stable.
That's said, I'm thinking of someday do one compilation for each major version (just for fun). But I'm not sure if it will be useful in any way. If a few people show interest, then I will put it in my plans.
I think it's more of an aesthetic issue than a utility one (with a single exception, the v0.9.8, but this version isn't good on linux, only on windows).
So I would like to know: what do you think about it?

**Comment by TotalCaesar659** [comment]
I haven't meant "a lot of verification and validations", I meant just one Appimage build from "stable" PCSX2 1.6.0 source, like in GIMP repo above (like GIMP_AppImage-release-2.10.18-x86_64.AppImage). I have a doubt that it should take more efforts that recurring building any unstable version.
> That result on the last version been almost always more stable.

Your words are reasonable, but many people give their priority for "stable" version first. This build would be like psychological present for them. And, if they tell about a bug in "stable" version, you always can answer "Try unstable one".
> That's said, I'm thinking of someday do one compilation for each major version (just for fun).

I can't follow you. Do you want to build almost 30 AppImages for [these "stable" versions](https://wiki.pcsx2.net/PCSX2#Release_history) (+ 1.6.0)? I've never asked for this (like Adam Jensen :-) and would be happy ony with just one 1.6.0 build, but I have nothing against it.
Perhaps, if you don't want to waste you time for it or I just misunderstand you, feel free to say about, I won't insist.

**Comment by ferion11** [comment]
Well, I understand your point. But you have to keep in mind that it isn't one iron rule for all applications. Some follow one principle of more recent is more stable like pcsx2, others like Google Chrome follow the stable/unstable format that you have describe.
That's said, just to note, I don't use this AppImage myself, so everything that I do here is just for fun, and for testing new ways of handle AppImages too.
Then about compile many versions is just one test for others AppImages, the ones that I use. And I'm talking about just the major versions, in the pcsx2 case, i think is v1.6.0, v1.4.0, v1.2.0, v1.0 and v0.9.8. This thinking is supported only by the fact that the official repository has one branch for each of these major versions, otherwise I wouldn't do it. So I don't have intent of keep doing it for many time.
If you like it, then you should support the pull requests that try to make it official. Like this one: https://github.com/PCSX2/pcsx2/pull/3236
and after that one, I will try to make another to incorporate the generation into the official repo (and possible archive this one).
But as I said before, this compilation isn't yet in my plans, it's still just a thought.

**Comment by TotalCaesar659** [comment]
There is no need to fix vulnerabilities in PCSX2 like in Chrome, so stable releases are not so bad for it, I guess.
> Then about compile many versions is just one test for others AppImages, the ones that I use. And I'm talking about just the major versions, in the pcsx2 case, i think is v1.6.0, v1.4.0, v1.2.0, v1.0 and v0.9.8.

Though I can't think of any reason for it but historical one (and for people with old PCs), why not? If you're sure.
>If you like it, then you should support the pull requests that try to make it official.

"Support" morally (by like) or technically (by developing it)? Well, If I had skills for making AppImages, I would do, so I have only the first way.
Any way, thank you very much for the detailed answer. Let's hope that PCSX2 developers will do their best for AppImage support.

**Comment by ferion11** [comment]
Support by like and comment, you would be surprise about the results that this can get. The pcsx2 devs don't want to make one official AppImage because they think that just little few users really care about this.

**Comment by ferion11** [comment]
I has made the the branch 1.6.x, you can get the result here:
https://github.com/ferion11/PCSX2_Appimage/releases/tag/continuous-1.6.x

**Comment by TotalCaesar659** [comment]
Thank you very much! It works alright.

**Comment by seffs** [comment]
Thank you for this release!
