### ISSUE TITLE
You should use old versions of Pango due to font format support.

### ISSUE THREAD

**Issue by ghost** [ferion11/PCSX2_Appimage#7]
Pango 1.44.x removed the displaying support for X11 bitmap fonts, which means that if you set the UI font to a bitmapped one (like Terminus), it will display empty glyphs.
You should use version 1.42 instead.

**Comment by ferion11** [comment]
That would be against upstream decisions. And I also think that X11 apps shouldn't use bitmapped fonts. I use Terminus on my console (the "ter-114n"), but for X11 apps, I think some like the Source fonts are far better (and have the license OFL-1.1):
https://adobe-fonts.github.io/source-sans-pro/
https://adobe-fonts.github.io/source-serif-pro/
https://adobe-fonts.github.io/source-code-pro/

**Comment by ghost** [comment]
Most of the people do not own a Hi-DPI monitor.
With outline fonts, if you enable antialiasing you get blurry text, and if you disable it you get out-of-shape text.
Bitmap fonts have no such problem.

**Comment by ferion11** [comment]
I don't have one Hi-DPI monitor either. I use good fonts because [Typography Matters for me](https://www.youtube.com/watch?v=tu4t9FKn9M4) (I need the Greek, Hebrew, and Latin to look good together here, because of the serious bible study, [like this](https://blog.logoscdn.com/wp-content/uploads/2017/10/image2-1-620x333.png)).
Your linux installation have font bugs or wrong configurations (by the way, not all linux fonts work the same way, then you have [to choose better ones](https://wiki.gentoo.org/wiki/Fontconfig#Picking_fonts) too). You can see this as an opportunity to learn while fixing your font system and choose better fonts (if you do it right, it will look very good, and you will be less tired from reading screen text too).
